document.addEventListener("DOMContentLoaded", async () => {
  const id=new URLSearchParams(location.search).get("id"), title=document.getElementById("detailTitle"), text=document.getElementById("detailText"), cover=document.getElementById("detailCover"), trailer=document.getElementById("trailer"), save=document.getElementById("detailSave");
  if(!id){title.textContent="Movie not found";text.textContent="No movie ID was provided.";return;}
  try{
    let m=await window.SFCatalog?.byId(id); if(!m) m=await SF.details(id);
    document.title=`${m.title||"Movie"} - ULMFlix`; title.textContent=m.title||"Movie"; text.textContent=m.overview||"No overview available."; cover.style.backgroundImage=`url("${SF.backdrop(m)}")`;
    const year=(m.release_date||"").slice(0,4), meta=document.getElementById("detailMeta"); if(meta)meta.textContent=`${year||"N/A"} • ★ ${Number(m.vote_average||0).toFixed(1)} • ${m.runtime?m.runtime+" min":"Movie"}`;
    const saved=await window.SFLibrary?.isSaved?.(Number(m.id)); save.textContent=saved?"♥ Saved to Watchlist":"♡ Add to Watchlist"; save.classList.toggle("active",!!saved);
    const later=document.getElementById("detailLater"); if(later){const laterSaved=await window.SFLibrary?.isWatchLater?.(Number(m.id)); later.textContent=laterSaved?"✓ In Watch Later":"＋ Watch Later"; later.onclick=async()=>{try{const added=await window.SFLibrary.toggleWatchLater(m.id);later.textContent=added?"✓ In Watch Later":"＋ Watch Later";}catch(e){alert(e.message||"Could not update Watch Later.")}};}
    save.onclick=async()=>{try{const added=await window.SFLibrary.toggleFavorite({id:m.id,title:m.title,release_date:m.release_date||"",release_year:m.release_year||year,vote_average:m.vote_average||0,poster_url:m.poster_url||m.poster_path||""});save.textContent=added?"♥ Saved to Watchlist":"♡ Add to Watchlist";save.classList.toggle("active",added);}catch(e){alert(e.message||"Could not update watchlist.")}};
    await window.SFLibrary?.track?.("movie_view",m.id,{title:m.title});
    const progress=await window.SFLibrary?.getProgress?.(m.id); if(progress?.position_seconds) window.__resumePosition=Number(progress.position_seconds);
    let premiumAllowed=true; if(m.is_premium&&window.SF_SUPABASE){const {data:{user}}=await window.SF_SUPABASE.auth.getUser(); if(!user) premiumAllowed=false; else {const {data:sub}=await window.SF_SUPABASE.from('subscriptions').select('status,current_period_end').eq('user_id',user.id).in('status',['active','trialing']).order('current_period_end',{ascending:false}).limit(1).maybeSingle(); premiumAllowed=Boolean(sub&&(!sub.current_period_end||new Date(sub.current_period_end)>new Date()));}}
    if(!premiumAllowed){trailer.innerHTML='<div class="status">🔒 Premium content. <a class="btn btn-red" href="earn.html">Subscribe to watch</a></div>';return;}
    if(m.video_url){let playable=m.video_url;if(String(playable).startsWith('storage://media/')){try{const session=await window.SF_SUPABASE.auth.getSession();const r=await fetch(`/api/video-url?movieId=${encodeURIComponent(m.id)}`,{headers:{Authorization:`Bearer ${session.data.session?.access_token||''}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Playback authorization failed.');playable=d.url;}catch(e){trailer.innerHTML=`<div class="status">${SF.escape(e.message)}</div>`;return;}}trailer.innerHTML=`<video controls playsinline preload="metadata" style="width:100%;max-height:70vh" src="${SF.escape(playable)}"></video>`;const v=trailer.querySelector("video");if(window.__resumePosition)v.addEventListener("loadedmetadata",()=>{try{v.currentTime=Math.min(window.__resumePosition,v.duration-1)}catch{}});v.addEventListener("timeupdate",()=>window.SFLibrary.saveProgress(m.id,v.currentTime,v.duration));}
    else {const t=(m.videos?.results||[]).find(v=>v.site==="YouTube"&&(v.type==="Trailer"||v.type==="Teaser"));trailer.innerHTML=t?`<iframe src="https://www.youtube.com/embed/${encodeURIComponent(t.key)}" title="Trailer for ${SF.escape(m.title)}" allowfullscreen></iframe>`:`<div class="status">No trailer is available for this title.</div>`;}
  }catch(err){title.textContent="Unable to load movie";text.textContent=err.message;}
});
