(function(){'use strict';
const KEY='ULMFlix_income_plan_v2', DB='ULMFlixIncomeDB', STORE='plans'; let CURRENT_UID='guest';
const PAGE_SIZE=30; let state={selected:[], page:1, query:'', category:'all', availability:'all'};
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:localStorage.getItem('ULMFlix_currency')||'USD',maximumFractionDigits:0}).format(Number(n)||0);
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function scopedKey(){return KEY+'_'+CURRENT_UID} function loadCache(){try{return JSON.parse(localStorage.getItem(scopedKey()))||[]}catch{return[]}}
function saveCache(){localStorage.setItem(scopedKey(),JSON.stringify(state.selected)); $('syncStatus').textContent=CURRENT_UID==='guest'?'Local':'Local + Online'}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function saveIndexed(){try{const d=await db();const tx=d.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);s.put({id:'current_'+CURRENT_UID,selected:state.selected,updatedAt:new Date().toISOString()});return true}catch(e){return false}}
async function loadIndexed(){try{const d=await db();return await new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get('current_'+CURRENT_UID);r.onsuccess=()=>res(r.result?.selected||null);r.onerror=()=>rej(r.error)})}catch{return null}}
async function persist(){saveCache();await saveIndexed()}
function notice(t){$('incomeNotice').textContent=t;clearTimeout(notice.t);notice.t=setTimeout(()=>$('incomeNotice').textContent='',3500)}
function categories(){const sel=$('incomeCategory');const cats=[...new Set(ULMFLIX_INCOME_OPTIONS.map(x=>x.category))];cats.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;sel.appendChild(o)})}
function filtered(){const q=state.query.toLowerCase();return ULMFLIX_INCOME_OPTIONS.filter(x=>(state.category==='all'||x.category===state.category)&&(state.availability==='all'||x.availability==='Varies by country')&&(!q||(x.name+' '+x.category+' '+x.description).toLowerCase().includes(q)))}
function render(){const list=filtered(), pages=Math.max(1,Math.ceil(list.length/PAGE_SIZE));state.page=Math.min(state.page,pages);const start=(state.page-1)*PAGE_SIZE;const frag=document.createDocumentFragment();list.slice(start,start+PAGE_SIZE).forEach(x=>{const card=document.createElement('article');card.className='income-card';const tag=document.createElement('span');tag.className='income-tag';tag.textContent=x.category;const h=document.createElement('h3');h.textContent=x.name;const p=document.createElement('p');p.textContent=x.description;const act=document.createElement('div');act.className='income-card-actions';const target=document.createElement('input');target.type='number';target.min='0';target.step='1';target.placeholder='Target/mo';const btn=document.createElement('button');btn.className='btn btn-dark';const exists=state.selected.find(s=>s.optionId===x.id);btn.textContent=exists?'Added':'Add';btn.disabled=!!exists;btn.onclick=()=>{state.selected.push({id:uid(),optionId:x.id,target:Number(target.value)||0,status:'planned'});persist().then(renderPlan);render()};act.append(target,btn);card.append(tag,h,p,act);frag.append(card)});const grid=$('incomeGrid');grid.replaceChildren(frag);$('pageLabel').textContent=`Page ${state.page} / ${pages}`;$('prevPage').disabled=state.page<=1;$('nextPage').disabled=state.page>=pages;$('optionCount').textContent=ULMFLIX_INCOME_OPTIONS.length+'+';$('selectedCount').textContent=state.selected.length;$('targetTotal').textContent=money(state.selected.reduce((a,s)=>a+s.target,0))}
function renderPlan(){const list=$('planList'),frag=document.createDocumentFragment();state.selected.forEach((s,i)=>{const o=ULMFLIX_INCOME_OPTIONS.find(x=>x.id===s.optionId);if(!o)return;const row=document.createElement('div');row.className='plan-row';const name=document.createElement('strong');name.textContent=o.name;const input=document.createElement('input');input.type='number';input.min='0';input.value=s.target||0;input.onchange=()=>{s.target=Number(input.value)||0;persist().then(render)};const select=document.createElement('select');['planned','active','paused','completed'].forEach(v=>{const op=document.createElement('option');op.value=v;op.textContent=v[0].toUpperCase()+v.slice(1);op.selected=s.status===v;select.append(op)});select.onchange=()=>{s.status=select.value;persist()};const del=document.createElement('button');del.className='btn btn-dark';del.textContent='Remove';del.onclick=()=>{state.selected.splice(i,1);persist().then(()=>{renderPlan();render()})};row.append(name,input,select,del);frag.append(row)});list.replaceChildren(frag);if(!state.selected.length){const e=document.createElement('p');e.className='muted';e.textContent='Add income streams above to build your plan.';list.append(e)}}
async function syncCloud(){const client=window.SF_SUPABASE;if(!client){notice('Online sync is not configured; your plan is safely stored locally.');return}try{const {data:{user}}=await client.auth.getUser();if(!user){notice('Sign in with your connected online account to sync securely.');return}$('syncStatus').textContent='Syncing…';const payload={user_id:user.id,plan:state.selected,updated_at:new Date().toISOString()};const {error}=await client.from('income_plans').upsert(payload,{onConflict:'user_id'});if(error)throw error;$('syncStatus').textContent='Online';notice('Income plan synced online and kept locally.')}catch(e){$('syncStatus').textContent='Local';notice('Cloud sync unavailable right now; local copy is still safe.')}}
function exportPlan(){const blob=new Blob([JSON.stringify({app:'ULMFlix',version:2,exportedAt:new Date().toISOString(),selected:state.selected},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ulmflix-income-plan.json';a.click();URL.revokeObjectURL(a.href)}
function importPlan(file){const r=new FileReader();r.onload=async()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.selected))throw 0;state.selected=d.selected.filter(x=>ULMFLIX_INCOME_OPTIONS.some(o=>o.id===x.optionId));await persist();render();renderPlan();notice('Income plan imported.')}catch{notice('Invalid income plan file.')}};r.readAsText(file)}
async function init(){
try{if(window.SF_SUPABASE){const r=await window.SF_SUPABASE.auth.getUser();CURRENT_UID=r.data.user?.id||'guest';}}catch{}
state.selected=loadCache();const idx=await loadIndexed();if(idx)state.selected=idx;categories();$('incomeSearch').oninput=e=>{state.query=e.target.value;state.page=1;render()};$('incomeCategory').onchange=e=>{state.category=e.target.value;state.page=1;render()};$('incomeAvailability').onchange=e=>{state.availability=e.target.value;state.page=1;render()};$('prevPage').onclick=()=>{if(state.page>1){state.page--;render()}};$('nextPage').onclick=()=>{state.page++;render()};$('syncIncomeBtn').onclick=syncCloud;$('exportIncomeBtn').onclick=exportPlan;$('importIncomeInput').onchange=e=>e.target.files[0]&&importPlan(e.target.files[0]);$('clearPlanBtn').onclick=async()=>{if(confirm('Clear all selected income streams?')){state.selected=[];await persist();render();renderPlan()}};$('addIncomeBtn').onclick=()=>window.scrollTo({top:document.querySelector('.income-grid').offsetTop-100,behavior:'smooth'});render();renderPlan()}
document.addEventListener('DOMContentLoaded',init);
})();
