(()=>{
  const q=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const localKey='sf_reviews';
  async function load(){
    const list=q('#reviewList'); if(!list)return;
    if(window.SF_SUPABASE){const {data,error}=await window.SF_SUPABASE.from('reviews').select('id,movie_id,movie_title,rating,body,created_at').eq('status','published').order('created_at',{ascending:false});if(!error&&data){list.innerHTML=data.length?data.map(r=>`<article class="review"><strong>${esc(r.movie_title)}</strong><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>${esc(r.body)}</p><div class="post-meta">Member • ${new Date(r.created_at).toLocaleDateString()}</div></article>`).join(''):'<p class="muted">No reviews yet.</p>';return;}}
    let a=[];try{a=JSON.parse(localStorage.getItem(localKey)||'[]')}catch{} list.innerHTML=a.length?a.slice().reverse().map(r=>`<article class="review"><strong>${esc(r.movie)}</strong><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>${esc(r.text)}</p><div class="post-meta">${esc(r.name||'Member')} • ${new Date(r.createdAt).toLocaleDateString()}</div></article>`).join(''):'<p class="muted">No reviews yet.</p>';
  }
  document.addEventListener('DOMContentLoaded',async()=>{await load();q('#publish')?.addEventListener('click',async()=>{const u=await window.SF_SUPABASE?.auth?.getUser?.();const user=u?.data?.user;if(!user){location.href='login.html?redirect=reviews.html';return}const movie=q('#movieTitle').value.trim(),body=q('#reviewText').value.trim(),rating=Number(q('#rating').value);if(!movie||body.length<20){q('#reviewMessage').hidden=false;q('#reviewMessage').textContent='Please enter a movie title and at least 20 characters.';return}if(window.SF_SUPABASE){const {error}=await window.SF_SUPABASE.from('reviews').insert({user_id:user.id,movie_title:movie,rating,body,status:'published'});if(error){q('#reviewMessage').hidden=false;q('#reviewMessage').textContent=error.message;return;}q('#reviewMessage').hidden=false;q('#reviewMessage').textContent='Review published.';}else{let a=[];try{a=JSON.parse(localStorage.getItem(localKey)||'[]')}catch{}a.push({id:crypto.randomUUID?.()||String(Date.now()),movie,text:body,rating,name:user.user_metadata?.name||user.email,createdAt:new Date().toISOString()});localStorage.setItem(localKey,JSON.stringify(a));q('#reviewMessage').hidden=false;q('#reviewMessage').textContent='Review published locally.';}q('#movieTitle').value='';q('#reviewText').value='';await load();});});
})();
