(function(){
  "use strict";
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const supabase=()=>window.SF_SUPABASE;
  async function session(){const {data:{session}}=await supabase().auth.getSession();return session;}
  async function adminRequest(path,options={}){const s=await session();if(!s)throw new Error('Session expired.');const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${s.access_token}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
  async function upload(file,userId,bucket='media'){if(!file)return '';if(file.size>100*1024*1024)throw new Error('Video/image file is too large (max 100 MB).');const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`movies/${crypto.randomUUID()}.${ext}`;const {error}=await supabase().storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(error)throw error;return bucket==='media'?`storage://media/${path}`:supabase().storage.from(bucket).getPublicUrl(path).data.publicUrl;}

  function nav(){document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'));}
  async function dashboard(){const el=id=>document.getElementById(id);if(!el('movieCount'))return;try{const {data:movies}=await supabase().from('movies').select('id,status,video_url,added_at').order('added_at',{ascending:false});const {count:userCount}=await supabase().from('profiles').select('id',{count:'exact',head:true});el('movieCount').textContent=movies?.length||0;el('publishedCount').textContent=movies?.filter(x=>x.status==='Published').length||0;el('userCount').textContent=userCount||0;el('videoCount').textContent=movies?.filter(x=>x.video_url).length||0;}catch(e){console.error(e)}}

  async function moviesPage(){const rows=document.getElementById('movieRows');if(!rows)return;const modal=document.getElementById('movieModal'),form=document.getElementById('movieForm');let list=[];
    async function load(){rows.innerHTML='<tr><td colspan="6" class="status">Loading…</td></tr>';const r=await adminRequest('/api/movies');list=r.movies||[];render();}
    function render(){const q=(document.getElementById('movieSearch')?.value||'').toLowerCase();const a=list.filter(m=>(`${m.title} ${m.status} ${(m.genres||[]).join(' ')}`).toLowerCase().includes(q));rows.innerHTML=a.length?a.map(m=>`<tr><td><img class="poster-thumb" src="${esc(m.poster_url||'../assets/images/placeholder-action.svg')}" onerror="this.src='../assets/images/placeholder-action.svg'"></td><td><strong>${esc(m.title)}</strong><br><small>${esc(m.release_year||'')}</small></td><td>${esc((m.genres||[]).join(', '))}</td><td><span class="badge ${m.status==='Published'?'green':''}">${esc(m.status)}</span></td><td>${m.video_url?'✓ Added':'Not Added'}</td><td><button class="btn btn-dark" data-edit="${m.id}">Edit</button> <button class="btn btn-danger" data-delete="${m.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="6" class="status">No movies found.</td></tr>';}
    function open(m){modal?.classList.add('open');form.reset();document.getElementById('movieId').value=m?.id||'';for(const [id,key] of [['title','title'],['year','release_year'],['genre','genres'],['poster','poster_url'],['trailer','trailer_url'],['video','video_url'],['description','description'],['status','status']]){const el=document.getElementById(id);if(!el)continue;el.value=key==='genres'?(m?.genres||[]).join(', '):(m?.[key]??(key==='status'?'Published':''));}document.getElementById('isPremium').checked=Boolean(m?.is_premium);document.getElementById('modalTitle').textContent=m?'Edit Movie':'Add New Movie';}
    window.closeMovieForm=()=>modal?.classList.remove('open');
    document.getElementById('addMovie')?.addEventListener('click',()=>open());document.getElementById('cancelMovie')?.addEventListener('click',window.closeMovieForm);document.getElementById('movieSearch')?.addEventListener('input',render);
    rows.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');try{if(edit)open(list.find(m=>String(m.id)===edit.dataset.edit));if(del&&confirm('Delete this movie permanently?')){await adminRequest('/api/movies?id='+encodeURIComponent(del.dataset.delete),{method:'DELETE'});await load();}}catch(err){alert(err.message)}});
    form?.addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('movieId').value;const posterFile=document.getElementById('posterFile')?.files?.[0],videoFile=document.getElementById('videoFile')?.files?.[0];try{let poster=document.getElementById('poster').value.trim(),video=document.getElementById('video').value.trim();if(posterFile)poster=await upload(posterFile,undefined,'posters');if(videoFile)video=await upload(videoFile,undefined,'media');const body={title:document.getElementById('title').value.trim(),release_year:Number(document.getElementById('year').value)||null,genres:document.getElementById('genre').value.split(',').map(x=>x.trim()).filter(Boolean),poster_url:poster,video_url:video,trailer_url:document.getElementById('trailer').value.trim(),description:document.getElementById('description').value.trim(),status:document.getElementById('status').value,is_premium:document.getElementById('isPremium').checked};await adminRequest(id?'/api/movies?id='+encodeURIComponent(id):'/api/movies',{method:id?'PATCH':'POST',body:JSON.stringify(id?{...body,id}:body)});window.closeMovieForm();await load();}catch(err){alert(err.message)}});load();}

  async function usersPage(){const rows=document.getElementById('userRows');if(!rows)return;try{const r=await adminRequest('/api/users');rows.innerHTML=(r.users||[]).map(u=>`<tr><td>${esc(u.profile?.display_name||u.email?.split('@')[0]||'User')}</td><td>${esc(u.email)}</td><td>${esc(u.profile?.role||'user')}</td><td>${u.email_confirmed_at?'Verified':'Pending'}</td></tr>`).join('')||'<tr><td colspan="4">No users.</td></tr>';}catch(e){rows.innerHTML=`<tr><td colspan="4">${esc(e.message)}</td></tr>`;}}

  document.addEventListener('DOMContentLoaded',()=>{nav();dashboard();moviesPage();usersPage();});
  window.SFAdmin={adminRequest,upload};
})();
