(()=>{
const DB='ULMFlixWorkspace', VER=1, STORE='items'; let db, current='root';
const $=id=>document.getElementById(id); const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result,s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('parent','parent');s.createIndex('type','type')};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function all(){return new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly').objectStore(STORE).getAll();t.onsuccess=()=>res(t.result);t.onerror=()=>rej(t.error)})}
function put(v){return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite').objectStore(STORE).put(v);t.onsuccess=()=>res(v);t.onerror=()=>rej(t.error)})}
function del(id){return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);t.onsuccess=()=>res();t.onerror=()=>rej(t.error)})}
async function seed(){const a=await all();if(!a.some(x=>x.id==='root'))await put({id:'root',type:'folder',name:'My Files',parent:null,createdAt:Date.now()})}
function fmt(n){if(!n)return '0 B';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(n<10&&i?1:0)+' '+u[i]}
async function render(){const a=await all(), folders=a.filter(x=>x.type==='folder'), items=a.filter(x=>x.parent===current&&x.id!=='root'); const f=folders.filter(x=>x.parent===current||x.id==='root'); $('folderList').innerHTML=folders.map(x=>`<div class="fm-item ${x.id===current?'active':''}"><button data-folder="${x.id}">📁 ${escapeHtml(x.name)}</button>${x.id!=='root'?`<button class="danger" data-del-folder="${x.id}">×</button>`:''}</div>`).join(''); $('currentFolderName').textContent=folders.find(x=>x.id===current)?.name||'My Files'; $('itemCount').textContent=`${items.length} item${items.length===1?'':'s'}`; $('itemGrid').innerHTML=items.length?items.map(x=>tile(x)).join(''):'<div class="fm-empty">No files or pages here yet.<br>Create a page, folder, or upload a file.</div>'; $('storageInfo').textContent=`${folders.length} folders • ${a.filter(x=>x.type==='file').length} files • ${a.filter(x=>x.type==='page').length} pages`;}
function tile(x){const icon=x.type==='folder'?'📁':x.type==='page'?'📄':'📎';return `<article class="fm-tile"><div><div style="font-size:28px">${icon}</div><strong>${escapeHtml(x.name)}</strong><div class="fm-muted">${x.type==='file'?fmt(x.size):x.type}</div></div><div class="fm-actions">${x.type==='folder'?`<button data-folder="${x.id}">Open</button>`:''}${x.type!=='folder'?`<button data-download="${x.id}">Download</button>`:''}<button class="danger" data-delete="${x.id}">Delete</button></div></article>`}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function createFolder(){const name=$('folderName').value.trim();if(!name)return alert('Enter a folder name.');await put({id:uid(),type:'folder',name,parent:current,createdAt:Date.now()});$('folderName').value='';close('folderModal');render()}
async function createPage(){const title=$('pageTitle').value.trim(), slug=($('pageSlug').value.trim()||title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''));if(!title)return alert('Enter a page title.');const content=$('pageContent').value||`<!doctype html><html><head><title>${escapeHtml(title)}</title></head><body><h1>${escapeHtml(title)}</h1></body></html>`;await put({id:uid(),type:'page',name:slug+'.html',title,slug,content,parent:current,createdAt:Date.now()});$('pageTitle').value='';$('pageSlug').value='';$('pageContent').value='';close('pageModal');render()}
async function upload(files){for(const f of files)await put({id:uid(),type:'file',name:f.name,mime:f.type,size:f.size,blob:f,parent:current,createdAt:Date.now()});render()}
async function download(id){const x=(await all()).find(i=>i.id===id);if(!x)return;let blob,name;if(x.type==='file'){blob=x.blob;name=x.name}else if(x.type==='page'){blob=new Blob([x.content],{type:'text/html;charset=utf-8'});name=x.name}else return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
async function remove(id){const a=await all(), children=a.filter(x=>x.parent===id);if(children.length&&!confirm('This folder contains items. Delete the folder and its contents?'))return;for(const x of children)await remove(x.id);await del(id);if(current===id)current='root';render()}
function close(id){$(id).classList.remove('open')};function open(id){$(id).classList.add('open')}
document.addEventListener('click',async e=>{const f=e.target.closest('[data-folder]');if(f){current=f.dataset.folder;render()}const d=e.target.closest('[data-download]');if(d)download(d.dataset.download);const x=e.target.closest('[data-delete]');if(x)remove(x.dataset.delete);const df=e.target.closest('[data-del-folder]');if(df)remove(df.dataset.delFolder);if(e.target.dataset.close)close(e.target.dataset.close)});
$('newFolder').onclick=()=>open('folderModal');$('newPage').onclick=()=>open('pageModal');$('saveFolder').onclick=createFolder;$('savePage').onclick=createPage;$('fileInput').onchange=e=>upload([...e.target.files]);$('downloadPageTemplate').onclick=()=>{const blob=new Blob(['<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ULMFlix Page</title></head><body><main><h1>New ULMFlix Page</h1><p>Edit this page in the File & Page Manager.</p></main></body></html>'],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ulmflix-page-template.html';a.click()};
const dz=$('dropzone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>upload([...e.dataTransfer.files]));$('menuBtn')?.addEventListener('click',()=>document.body.classList.toggle('sidebar-open'));
openDB().then(seed).then(render).catch(err=>{console.error(err);alert('Your browser does not support the workspace database.')});
})();